# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab85247456775762e8cd02fb6aac52dc84760751ca8093204da0739b2f07f48dca4b6eb6b63e00c878467ed1c5cf3b9840a93fd7543919bf9505f2fb594d9550

test:
  secret_key_base: 5e851acaecde6589224c2aef201a3c28dfaf244605ada4d239de96f742b2350dca35c749dfbdb5961125e37a59ec9220841d4c8de2451c4f4bd12cf2b5fd270f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
